notifications:
  email: false
language: node_js
node_js:
  - "9.3"
services:
  - mongodb
cache:
  directories:
    - node_modules
install:
  - npm install --save cors
  - npm install -g codecov
before_script:
  - npm install -g jest-cli
script:
  - jest test --ci --colors && codecov
