notifications:
  email: false
sudo: required
language: node_js
node_js:
  - "8.6"
cache:
  directories:
    - node_modules
before_script:
  - node server.js
  - npm install -g jest
script:
  - jest test
