notifications:
  email: false
sudo: required
language: node_js
node_js:
  - "8.6"
services:
  - mongodb
install:
  - npm install -g codecov
before_script:
  - npm install -g jest-cli
script:
  - jest test --ci --colors && codecov
